easy_admin:
    formats:
        date: 'd/m/Y'
        datetime: 'd/m/Y h:i'
        time: 'h:i'
    translation_domain: 'messages'
    site_name: 'ExLibris'
    design:
        color_scheme: 'light'
        brand_color: '#f19f26'
        menu:            
            - { entity: 'Livres', icon: 'book' }
            - { entity: 'Auteurs', icon: 'user-circle' }
            - { entity: 'Editeurs', icon: 'address-book' }
            - { entity: 'Categories', label: 'Catégories', icon: 'address-card' }
            - { entity: 'Avis', icon: 'comment' }
            - { entity: 'Commandes', icon: 'envelope' }
            # - { entity: 'LignesCde', label: 'Lignes de commande', icon: 'copy' }
            - { entity: 'MouvStock', label: 'Mouvements de stock', icon: 'tag' }
            - { entity: 'Actu', label: 'Actualités', icon: 'book' }
            - { entity: 'User', label: 'Utilisateurs', icon: 'user' }
            - { entity: 'Promo', label: 'Promotions', icon: 'tag' }
    entities:
       # List the entity class name you want to manage
        Livres:
            class: App\Entity\Livres
            list:
                title: admin.livres.title
                fields:
                    - { property: 'titre', label: admin.livres.titre, type: 'text' }
                    - { property: 'auteur', label: admin.livres.auteur}
                    - { property: 'date_parution', label: admin.livres.parution}
                    - { property: 'prixTtc', label: admin.livres.prixttc }
                    - { property: 'est_conseil', label: admin.livres.estconseil}
                    - { property: 'active', label: admin.livres.active}
                    - { property: 'image', type: image, label: admin.livres.image, base_path: '%app.path.livres_images%' }
            new:
                fields:
                    - { property: 'isbn', label: admin.livres.isbn, type: 'text'}
                    - { property: 'titre', label: admin.livres.titre, type: 'text' }
                    - { property: 'auteur', label: admin.livres.auteur}
                    - { property: 'editeur', label: admin.livres.editeur}
                    - { property: 'categorie', label: admin.livres.categorie }
                    - { property: 'nbPages', label: admin.livres.nbpages, type: 'integer' }
                    - { property: 'prixTtc', label: admin.livres.prixttc, type: 'money', type_options: { currency: 'EUR' } }
                    - { property: 'date_parution', label: admin.livres.parution, type: 'date'}
                    - { property: 'est_conseil', label: admin.livres.estconseil}
                    - { property: 'active', label: admin.livres.active}
                    - { property: 'resume', label: admin.livres.resume}
                    - { property: 'imageFile', type: 'vich_image', label: admin.livres.image }
            edit:
                fields:
                    - { property: 'isbn', label: admin.livres.isbn, type: 'text'}
                    - { property: 'titre', label: admin.livres.titre, type: 'text' }
                    - { property: 'auteur', label: admin.livres.auteur}
                    - { property: 'editeur', label: admin.livres.editeur}
                    - { property: 'categorie', label: admin.livres.categorie }
                    - { property: 'nbPages', label: admin.livres.nbpages, type: 'integer' }
                    - { property: 'prixTtc', label: admin.livres.prixttc, type: 'money', type_options: { currency: 'EUR' } }
                    - { property: 'date_parution', label: admin.livres.parution, type: 'date'}
                    - { property: 'est_conseil', label: admin.livres.estconseil}
                    - { property: 'note_moyenne', label: admin.livres.note_moyenne}
                    - { property: 'active', label: admin.livres.active}
                    - { property: 'resume', label: admin.livres.resume}
                    - { property: 'imageFile', type: 'vich_image', label: admin.livres.image }
        User:
            class: App\Entity\User
            disabled_actions: ['new']
            list:
                title: admin.user.title
                actions: ['show']
                fields:
                    - { property: 'username', label: admin.user.username, type: 'text'}
                    - { property: 'email', label: admin.user.email, type: 'email' }
                    - { property: 'roles', label: admin.user.roles}
                    - { property: 'createdAt', label: admin.user.createdat}
            edit:
                fields:
                    - { property: 'roles', label: admin.user.roles, type: 'choice', type_options: { multiple: true, expanded: true, choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN'}}}
        
        Auteurs:
            class: App\Entity\Auteurs
            list:
                title: admin.auteurs.title
                fields:
                    - { property: 'prenomAuteur', label: admin.auteurs.prenom, type: 'text' }
                    - { property: 'nomAuteur', label: admin.auteurs.nom, type: 'text'}
                    - { property: 'biographieAuteur', label: admin.auteurs.bio}
                    - { property: 'image', type: image, label: admin.auteurs.photo, base_path: '%app.path.auteurs_images%' }
                    - { property: 'livres', label: admin.auteurs.livres, type_options: { by_reference: false} }
            new:
                fields:
                    - { property: 'prenomAuteur', label: admin.auteurs.prenom, type: 'text' }
                    - { property: 'nomAuteur', label: admin.auteurs.nom, type: 'text'}
                    - { property: 'biographieAuteur', label: admin.auteurs.bio}
                    - { property: 'imageFile', type: 'vich_image', label: admin.auteurs.photo }
            edit:
                fields:
                    - { property: 'prenomAuteur', label: admin.auteurs.prenom, type: 'text' }
                    - { property: 'nomAuteur', label: admin.auteurs.nom, type: 'text'}
                    - { property: 'biographieAuteur', label: admin.auteurs.bio}
                    - { property: 'imageFile', type: 'vich_image', label: admin.auteurs.photo }      
                    
        Editeurs:
            class: App\Entity\Editeurs
            list:
                title: admin.editeurs.title
                actions: ['show']
                fields:
                    - { property: 'nomEditeur', label: admin.editeurs.nom, type: 'text' }
                    - { property: 'livres', label: admin.editeurs.livres, type_options: { by_reference: false} }
            new:
                fields:
                    - { property: 'nomEditeur', label: admin.editeurs.nom, type: 'text' }
            edit:
                fields:
                    - { property: 'nomEditeur', label: admin.editeurs.nom, type: 'text' }
        Categories:
            class: App\Entity\Categories         
            list:
                title: admin.categories.title
                actions: ['show']
                fields:
                    - { property: 'LibelleCategorie', label: admin.categories.libelle, type: 'text' }
                    - { property: 'livres', label: admin.categories.livres, type_options: { by_reference: false} }
            new:
                fields:
                    - { property: 'LibelleCategorie', label: admin.categories.libelle, type: 'text' }
            edit:
                fields:
                    - { property: 'LibelleCategorie', label: admin.categories.libelle, type: 'text' }
            
        Avis:
            class: App\Entity\Avis
            disabled_actions: ['new']
            list:
                title: admin.avis.title
                fields:
                    - { property: 'user', label: admin.avis.user }
                    - { property: 'livre', label: admin.avis.livre }
                    - { property: 'dateavis', label: admin.avis.dateavis, type: 'date' }
                    - { property: 'note', label: admin.avis.note }
            show:
                fields:
                    - { property: 'user', label: admin.avis.user }
                    - { property: 'livre', label: admin.avis.livre }
                    - { property: 'dateavis', label: admin.avis.dateavis, type: 'date' }
                    - { property: 'commentaire', label: admin.avis.commentaire }
                    - { property: 'note', label: admin.avis.note }
            edit:
                fields:
                    - { property: 'user', label: admin.avis.user }
                    - { property: 'livre', label: admin.avis.livre }
                    - { property: 'dateavis', label: admin.avis.dateavis, type: 'date' }
                    - { property: 'commentaire', label: admin.avis.commentaire }
                    - { property: 'note', label: admin.avis.note }


        Commandes:
            class: App\Entity\Commandes
            disabled_actions: ['new']
            list:
                title: admin.commandes.title
                fields:
                    - { property: 'user', label: admin.commandes.user }
                    - { property: 'datecde', label: admin.commandes.datecde, type: 'datetime' }
                    - { property: 'totalttccde', label: admin.commandes.totalttccde }                    
                    # - { property: 'lignescdes', type_options: { by_reference: false} }
            edit:
                actions: ['-delete']
                fields:
                    - { property: 'datecde', label: admin.commandes.datecde, type: 'datetime' }
                    - { property: 'remise', label: admin.commandes.remise }
                    - { property: 'totalhtcde', label: admin.commandes.totalhtcde, type: 'money', type_options: { currency: 'EUR' } }
                    - { property: 'tvacde', label: admin.commandes.tvacde, type: 'money', type_options: { currency: 'EUR' } }
                    - { property: 'totalttccde', label: admin.commandes.totalttccde, type: 'money', type_options: { currency: 'EUR' } }
                    - { property: 'user', label: admin.commandes.user }
                    - { property: 'lignescdes',label: admin.commandes.lignescde, type: 'collection', type_options: { entry_type: 'App\Form\LignesCdeType', by_reference: false } }

        LignesCde:
            class: App\Entity\LignesCde
            list:
                title: admin.lignescde.title
        MouvStock:
            class: App\Entity\MouvStock
            list:
                title: admin.mouvstock.title
                actions: ['show']
        Actu:
            class: App\Entity\Actu
            list:
                title: admin.actu.title
                actions: ['show']
                fields:
                    - { property: 'titre', label: admin.actu.titre, type: 'text' }
                    - { property: 'accroche', label: admin.actu.accroche, type: 'text'}
                    - { property: 'image', type: image, label: admin.actu.image, base_path: '%app.path.actu_images%' }
                    - { property: 'createdAt', label: admin.actu.createdat}
                    - { property: 'updatedAt', label: admin.actu.updatedat}
            show:
                title: admin.actu.title
                fields:
                    - { property: 'titre', label: admin.actu.titre, type: 'text' }
                    - { property: 'accroche', label: admin.actu.accroche, type: 'text'}
                    - { property: 'contenu', label: admin.actu.contenu }
                    - { property: 'image', type: image, label: admin.actu.image, base_path: '%app.path.actu_images%' }
                    - { property: 'createdAt', label: admin.actu.createdat}
            new:
                fields:
                    - { property: 'titre', label: admin.actu.titre, type: 'text' }
                    - { property: 'accroche', label: admin.actu.accroche, type: 'text'}
                    - { property: 'contenu', label: admin.actu.contenu, type: 'textarea'}
                    - { property: 'imageFile', type: 'vich_image', label: admin.actu.image }
            edit:
                fields:
                    - { property: 'titre', label: admin.actu.titre, type: 'text' }
                    - { property: 'accroche', label: admin.actu.accroche, type: 'text'}
                    - { property: 'contenu', label: admin.actu.contenu, type: 'textarea'}
                    - { property: 'imageFile', type: 'vich_image', label: admin.actu.image }
        Promo:
            class: App\Entity\Promo
