easy_admin:
    formats:
        date: 'd/m/Y'
        datetime: 'd/m/Y h:i'
        time: 'h:i'
    translation_domain: 'messages'
    site_name: 'ExLibris'
    design:
        color_scheme: 'light'
        brand_color: '#f19f26'
        menu:
            - { entity: 'User', label: 'Utilisateurs', icon: 'user' }
            - { entity: 'livres', icon: 'book' }
            - { entity: 'Auteurs', icon: 'user-circle' }
            - { entity: 'Editeurs', icon: 'address-book' }
            - { entity: 'Categories', label: 'Catégories', icon: 'address-card' }
            - { entity: 'Avis', icon: 'comment' }
            - { entity: 'Commandes', icon: 'envelope' }
            - { entity: 'LignesCde', label: 'Lignes de commande', icon: 'copy' }
            - { entity: 'MouvStock', label: 'Mouvements de stock', icon: 'tag' }
    entities:
       # List the entity class name you want to manage
        User:
            class: App\Entity\User
            disabled_actions: ['new']
            list:
                title: admin.user.title
                fields:
                    - { property: 'username', label: admin.user.username, type: 'text'}
                    - { property: 'email', label: admin.user.email, type: 'email' }
                    - { property: 'roles', label: admin.user.roles}
                    - { property: 'createdAt', label: admin.user.createdat}
            edit:
                fields:
                    - { property: 'roles', label: admin.user.roles, type: 'choice', type_options: { multiple: true, expanded: true, choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN'}}}
        livres:
            class: App\Entity\livres
            list:
                title: admin.livres.title
                fields:
                    - { property: 'titre', label: admin.livres.titre, type: 'text' }
                    - { property: 'isbn', label: admin.livres.isbn, type: 'text'}
                    - { property: 'date_parution', label: admin.livres.parution}
                    - { property: 'prixHt', label: admin.livres.prixht }
                    - { property: 'est_conseil', label: admin.livres.estconseil}
                    - { property: 'active', label: admin.livres.active}
                    - { property: 'image', type: image, label: admin.livres.image, base_path: '%app.path.livres_images%' }
            new:
                fields:
                    - { property: 'isbn', label: admin.livres.isbn, type: 'text'}
                    - { property: 'titre', label: admin.livres.titre, type: 'text' }
                    - { property: 'auteur', label: admin.livres.auteur}
                    - { property: 'editeur', label: admin.livres.editeur}
                    - { property: 'categories', label: admin.livres.categories, type_options: { by_reference: false} }
                    - { property: 'nbPages', label: admin.livres.nbpages, type: 'integer' }
                    - { property: 'prixHt', label: admin.livres.prixht }
                    - { property: 'date_parution', label: admin.livres.parution, type: 'date'}
                    - { property: 'est_conseil', label: admin.livres.estconseil}
                    - { property: 'active', label: admin.livres.active}
                    - { property: 'resume', label: admin.livres.resume}
                    - { property: 'imageFile', type: 'vich_image', label: admin.livres.image }
            edit:
                fields:
                    - { property: 'isbn', label: admin.livres.isbn, type: 'text'}
                    - { property: 'titre', label: admin.livres.titre, type: 'text' }
                    - { property: 'auteur', label: admin.livres.auteur}
                    - { property: 'editeur', label: admin.livres.editeur}
                    - { property: 'categories', label: admin.livres.categories, type_options: { by_reference: false} }
                    - { property: 'nbPages', label: admin.livres.nbpages, type: 'integer' }
                    - { property: 'prixHt', label: admin.livres.prixht }
                    - { property: 'date_parution', label: admin.livres.parution, type: 'date'}
                    - { property: 'est_conseil', label: admin.livres.estconseil}
                    - { property: 'active', label: admin.livres.active}
                    - { property: 'resume', label: admin.livres.resume}
                    - { property: 'imageFile', type: 'vich_image', label: admin.livres.image }
        Auteurs:
            class: App\Entity\Auteurs
            list:
                title: admin.auteurs.title
        Editeurs:
            class: App\Entity\Editeurs
            list:
                title: admin.editeurs.title
        Categories:
            class: App\Entity\Categories
            list:
                title: admin.categories.title
        Avis:
            class: App\Entity\Avis
            list:
                title: admin.avis.title
        Commandes:
            class: App\Entity\Commandes
            list:
                title: admin.commandes.title
        LignesCde:
            class: App\Entity\LignesCde
            list:
                title: admin.lignescde.title
        MouvStock:
            class: App\Entity\MouvStock
            list:
                title: admin.mouvstock.title
