vich_uploader:
    db_driver: orm

    mappings:
       livres_images:
           uri_prefix: '%app.path.livres_images%'
           upload_destination: '%kernel.project_dir%/public/images/livres'
           delete_on_remove: false  # determine whether to delete file upon removal of entity
           delete_on_update: false  # determine whether to delete the file upon update of entity
       auteurs_images:
           uri_prefix: '%app.path.auteurs_images%'
           upload_destination: '%kernel.project_dir%/public/images/auteurs'
           delete_on_remove: false
           delete_on_update: false
       actu_images:
           uri_prefix: '%app.path.actu_images%'
           upload_destination: '%kernel.project_dir%/public/images/actu'
           delete_on_remove: false
           delete_on_update: false
