vich_uploader:
    db_driver: orm

    mappings:
       livres_images:
           uri_prefix: '%app.path.livres_images%'
           upload_destination: '%kernel.project_dir%/public/images/livres'
       auteurs_images:
           uri_prefix: '%app.path.auteurs_images%'
           upload_destination: '%kernel.project_dir%/public/images/auteurs'
       actu_images:
                  uri_prefix: '%app.path.actu_images%'
                  upload_destination: '%kernel.project_dir%/public/images/actu'
